version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:15"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 15.0.0
  - dependency-name: fastify
    versions:
    - 3.11.0
    - 3.12.0
    - 3.13.0
    - 3.14.0
    - 3.14.1
    - 3.14.2
  - dependency-name: typeorm
    versions:
    - 0.2.30
    - 0.2.31
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: fastify-static
    versions:
    - 3.4.0
    - 4.0.0
